### PR TITLE
support mixed rules

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by crazy-sam** [comment]
Wow, cool, thanks. This thing has at least one bug in it, one that I've fixed and just haven't pushed. Irresponsible of me, to be sure, but I didn't think anyone was using it. I'll have to push it / them, I guess. 
A CFG is: https://en.wikipedia.org/wiki/Generalized_context-free_grammar ? Why on Earth would you want to quickly find a degree of similarity between sets of rules? But I should know better than to ask :)
This is going to take a bit for me to warm up on, so to speak. I may just accept it all as-is, and let tests flush out bugs. Do you have any tests? I'd appreciate some of those (I need my own for the original, too).

**Comment by crazy-sam** [comment]
(This time with feeling.)
Wow, cool, thanks. This thing has at least one bug in it, one that I've fixed and just haven't pushed. Irresponsible of me, to be sure, but I didn't think anyone was using it. I'll have to push it / them, I guess.
A CFG is: https://en.wikipedia.org/wiki/Generalized_context-free_grammar ? Why on Earth would you want to quickly find a degree of similarity between sets of rules? But I should know better than to ask :)
This is going to take a bit for me to warm up on, so to speak. I may just accept it all as-is, and let tests flush out bugs. Do you have any tests? I'd appreciate some of those (I need my own for the original, too).

**Comment by mjpost** [comment]
Sorry, I inadvertently created this PR against your repo instead of my own master branch. But now I can't seem to find your comment here, I only have it in email.

So first, thanks for this very nice code! 

I want to support CFGs with rules whose righthand sides have intermingled terminals and nonterminals, e.g.,

    NP → the ADJ boy

Such rules are not found in the Penn Treebank (where all lexical items have a parent preterminal), but occur in other settings, for example, in the source- or target-side projection of synchronous grammars learned in machine translation (https://www.aclweb.org/anthology/N04-1035/). I also want to support when the terminal and nonterminal sets are not disjoint.

Part of the reason is that i want to do tree kernels on trees that have been chopped off at a certain depth, which leaves the situation above.

If you think you'd like this, I can reopen the PR from my master branch, which has these changes merged in now. Then you could at least look at it.

**Comment by JDonner** [comment]
*cough*
Wow, cool, thanks. This thing has at least one bug in it, one that I've fixed and just haven't pushed. Irresponsible of me, to be sure, but I didn't think anyone was using it. I'll have to push it / them, I guess.
A CFG is: https://en.wikipedia.org/wiki/Generalized_context-free_grammar ? Why on Earth would you want to quickly find a degree of similarity between sets of rules? But I should know better than to ask :)
This is going to take a bit for me to warm up on, so to speak. I may just accept it all as-is, and let tests flush out bugs. Do you have any tests? I'd appreciate some of those (I need better ones for the original, too).

**Comment by JDonner** [comment]
Yeah, I commented earlier under a different account. I think I prefer your keeping it separate, but I should fix my known bug(s), add my new comments, and write my more thorough tests. You may want to watch and take up those, where they're relevant. And I'm happy to point people to your code. Good stuff, you never know how code is going to be used.

**Comment by mjpost** [comment]
Sounds fine to me. Another bug is that your tree lexer cannot handle numbers or general UTF-8 characters. You may want to take my [more general definition of a letter](https://github.com/mjpost/TreeKernel/blob/298c87bcf452efad2a899366925e874217a7f0a4/tree-parser/tree_lexer.h#L43).

```c++
   bool isLETTER() {
     return (c != '(' and c != ')' and c != ' ');
   }
```

**Comment by mjpost** [comment]
Also, your definition of `productions_equal()` does not test that the lefthand-side of the productions match (it only tests the child sequences). I suspect this is not a problem in the Penn treebank but it is one more generally.

https://github.com/JDonner/TreeKernel/blob/282c376d935d969c6e647bea2f2016e083d626de/tree-kernel/node.cpp#L49

**Pull request closed without merging**
